In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Real estate.csv')
df.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [3]:
df.columns

Index(['No', 'X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],
      dtype='object')

In [4]:
df.drop('No', axis=1, inplace=True)

y = mx + c

y = m1x1 + m2x2 + m3x3 + .... + c

x is feature

m1,m2,m3 are the weights of each feature

In [5]:
X = df.drop('Y house price of unit area', axis=1) #features
y = df['Y house price of unit area'] #target

In [6]:
y

0      37.9
1      42.2
2      47.3
3      54.8
4      43.1
       ...
409    15.4
410    50.0
411    40.6
412    52.5
413    63.9
Name: Y house price of unit area, Length: 414, dtype: float64

In [7]:
#Train Test Split
''' 100
test_size = 0.2

X_train 80
X_test 20
y_train 80
y_test 20
'''
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
model = LinearRegression()

In [10]:
model.fit(X_train, y_train)

LinearRegression()

In [11]:
y_pred = model.predict(X_test)

In [12]:
y_pred

array([47.88625422, 41.16404556, 44.27301439, 40.19761542, 27.51326511,
       45.10953115, 44.63293274, 46.36346234, 23.62063133, 54.33444894,
       34.07416461, 36.54533193, 37.55154254, 23.2794052 , 35.26614165,
       34.38327747, 43.35633504, 45.40740539, 30.07083159, 44.09191493,
        0.73505984, 34.99271686, 48.22735154, 45.48646485, 11.5995282 ,
       39.69783664, 12.71276251, 42.91282893, 34.93451401, 37.27964515,
       13.17842185, 40.12708486, 35.21883505, 27.71588924, 46.40090931,
       31.21941994, 50.90046891, 14.07339433, 49.05344276, 40.0538446 ,
       38.24588962, 40.63256441, 47.01634759, 37.65598977, 39.85801839,
       46.88588156, 43.7241343 , 20.94434531, 47.41546271, 45.40608841,
       48.33783579, 48.98845389, 42.27403852, 42.5841908 , 36.04088185,
       14.95491907, 36.61494629, 34.88196676, 28.33519081, 45.91188076,
       33.19268817, 32.18910095, 14.95491907,  8.86547927, 10.36079881,
       34.11119212, 28.48186875, 46.59826043, 32.96743316, 31.47635439,
       45.75168852, 38.1732971 , 45.83734855, 45.10711423, 34.85434095,
       37.43148997, 38.12216764, 37.54923793, 40.3686992 , 33.09139633,
       42.32783358, 43.35398473, 28.43979763])

In [13]:
y_test

358    45.1
350    42.3
373    52.2
399    37.3
369    22.8
       ...
31     25.0
283    23.5
157    35.6
203    46.1
208    26.2
Name: Y house price of unit area, Length: 83, dtype: float64

In [14]:
from sklearn.metrics import mean_squared_error, r2_score

In [15]:
mse = mean_squared_error(y_test, y_pred)
mse

53.505619124504506

In [16]:
#r2: 0-1, closer to 1: model is better
r2 = r2_score(y_test, y_pred)
r2

0.6810580555095801

In [17]:
train_pred = model.predict(X_train) #data is seen by the model
test_pred = model.predict(X_test) #data is unseen for the model

In [18]:
print('R2 score train:', r2_score(y_train, train_pred))
print('R2 score test:', r2_score(y_test, test_pred))

R2 score train: 0.5581197274607117
R2 score test: 0.6810580555095801

In [20]:
X

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude
0,2012.917,32.0,84.87882,10,24.98298,121.54024
1,2012.917,19.5,306.59470,9,24.98034,121.53951
2,2013.583,13.3,561.98450,5,24.98746,121.54391
3,2013.500,13.3,561.98450,5,24.98746,121.54391
4,2012.833,5.0,390.56840,5,24.97937,121.54245
...,...,...,...,...,...,...
409,2013.000,13.7,4082.01500,0,24.94155,121.50381
410,2012.667,5.6,90.45606,9,24.97433,121.54310
411,2013.250,18.8,390.96960,7,24.97923,121.53986
412,2013.000,8.1,104.81010,5,24.96674,121.54067
413,2013.500,6.5,90.45606,9,24.97433,121.54310

R2 compares:
Your model
vs
A dumb baseline ( predicting the avg)

marks=[40,50,60]

avg = 50

baseline prediction -> 50 for all

if your model is not better than avg -> it's useless
R² = 1 - (SS res / SS tot)

SS res = Residual Sum of Squares
SUM (y actual - y predicted)²

SS tot = Total Sum of Squares
SUM (y actual - y mean)²

R² tells us how much better we are compared to just predicting the average

R²=1 Perfect model
predictions = actual values

R²=0 Same as predicting mean -> useless model

R²=0.7 -> Model explains 70% of variation

R² < 0 -> Worse than average, model is garbage

High R² does not always mean good model

Generalization:
the goal the ML is not to memorize data.
the goal is to perform well on new, unseen data. This is called generalization.

Overfitting:

it happens when a model memorizes the training data instead of learning patterns.

Very high training performance
Poor test performance

Underfitting:

happens when model is too simple to learn patterns.

Low training R2
Low testing R2

Drop the MRT column and retrain the model
Calculate the R2

3. Use only house age as input, retrain the model and calculate R2